name: Update README

on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

runs-on: ubuntu-latest
jobs:
 build:
  update-readme:
    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v4.2.2
  - uses: marygarcia162/github-activity-readme
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
